struct vector;
struct Args;
struct Target;
struct TargetMachine;
struct Module;
struct LLVMContext;
struct IRBuilder;
struct StructType;
struct llvm_Type;
struct PointerType;
struct ArrayType;
struct FunctionType;
struct LinkageTypes;
struct Function;
struct Argument;
struct AttrKind;
struct Value;
struct BasicBlock;
struct PHINode;

struct DICompileUnit;
struct DIFile;
struct DISubprogram;
struct DISubroutineType;
struct DIType;
struct DICompositeType;
struct DIDerivedType;
struct DIScope;
struct Metadata;
struct Metadata_vector;
struct DILocalVariable;
struct DIExpression;
struct DILocation;
struct StructLayout;

extern{
    func make_vec(): vector*;
    func vec_push(vec: vector*, elem: llvm_Type*);
    func make_args(): Args*;
    func args_push(vec: Args*, elem: Value*);

    func getDefaultTargetTriple(ptr: i8*): i32;
    func InitializeAllTargetInfos();
    func InitializeAllTargets();
    func InitializeAllTargetMCs();
    func InitializeAllAsmParsers();
    func InitializeAllAsmPrinters();
    func lookupTarget(triple: i8*): Target*;
    func createTargetMachine(triple: i8*): TargetMachine*;
    func make_module(name: i8*, tm: TargetMachine*, triple: i8*): Module*;
    func make_ctx(): LLVMContext*;
    func make_builder(): IRBuilder*;
    func emit_llvm(out: i8*);
    func emit_object(name: i8*, tm: TargetMachine*, triple: i8*);

    func init_dbg();
    func createFile(file: i8*, dir: i8*): DIFile*;
    func createCompileUnit(file: DIFile*): DICompileUnit*;
    func SetCurrentDebugLocation(scope: DIScope*, line: i32, pos: i32);
    func createObjectPointerType(type: DIType*): DIType*;
    func Metadata_vector_new(): Metadata_vector*;
    func Metadata_vector_push(vec: Metadata_vector*, elem: Metadata*);
    func createSubroutineType(tys: Metadata_vector*): DISubroutineType*;
    func make_spflags(is_main: bool): i32;
    func createFunction(scope: DIScope*, name: i8*, linkage_name: i8*, file: DIFile*, line: i32, ft: DISubroutineType*, spflags: i32): DISubprogram*;
    func setSubprogram(f: Function*, sp: DISubprogram*);
    func finalizeSubprogram(sp: DISubprogram*);
    func createParameterVariable(scope: DIScope*, name: i8*, idx: i32, file: DIFile*, line: i32, type: DIType*, preserve: bool): DILocalVariable*;
    func DILocation_get(scope: DIScope*, line: i32, pos: i32): DILocation*;
    func createExpression(): DIExpression*;
    func insertDeclare(value: Value*, var_info: DILocalVariable*, expr: DIExpression*, loc: DILocation*, bb: BasicBlock*);
    func createStructType(scope: DIScope*, name: i8*, file: DIFile*, line: i32, size: i64, elems: Metadata_vector*): DICompositeType*;
    func get_di_null(): DIType*;
    func get_null_scope(): DIScope*;
    func createBasicType(name: i8*, size: i64, enco: i32): DIType*;
    func DW_ATE_boolean(): i32;
    func DW_ATE_signed(): i32;
    func DW_ATE_unsigned(): i32;
    func DW_ATE_float(): i32;
    func createPointerType(elem: DIType*, size: i64): DIType*;
    func getOrCreateSubrange(lo: i64, count: i64): Metadata*;
    func createArrayType(size: i64, ty: DIType*, elems: Metadata_vector*): DIType*;
    func createMemberType(scope: DIScope*, name: i8*, file: DIFile*, line: i32, size: i64, off: i64, ty: DIType*): DIDerivedType*;
    func DIType_getSizeInBits(ty: DIType*): i64;
    func getStructLayout(st: StructType*): StructLayout*;
    func getElementOffsetInBits(sl: StructLayout*, idx: i32): i64;
    func replaceElements(st: DICompositeType*, elems: Metadata_vector*);
    func createVariantPart(scope: DIScope*, name: i8*, file: DIFile*, line: i32, size: i64, disc: DIDerivedType*, elems: Metadata_vector*): DICompositeType*;
    func createVariantMemberType(scope: DIScope *, name: i8*, file: DIFile *, line: i32, size: i64, off: i64, idx: i32, ty: DIType *): DIDerivedType*;


    func make_struct_ty(name: i8*): StructType*;
    func make_struct_ty2(name: i8*, elems: vector*): StructType*;
    func setBody(st: StructType*, elems: vector*);
    func getSizeInBits(st: StructType*): i32;
    func getPrimitiveSizeInBits(st: llvm_Type*): i32;
    func getInt(bits: i32): llvm_Type*;
    func makeInt(val: i64, bits: i32): Value*;
    func getPointerTo(type: llvm_Type*): llvm_Type*;
    func getArrTy(elem: llvm_Type*, size: i32): ArrayType*; 
    func getVoidTy(): llvm_Type*;
    func isPointerTy(type: llvm_Type*): bool;
    func getPtr(): llvm_Type*;
    func Value_isPointerTy(val: Value*): bool;
    
    func make_ft(ret: llvm_Type*, args: vector*, vararg: bool): FunctionType*;
    func ext(): i32;
    func odr(): i32;
    func make_func(fr: FunctionType*, l: i32, name: i8*): Function*;
    func get_arg(f: Function*, i: i32): Argument*;
    func arg_attr(a: Argument* , at: i32*);
    func get_sret(): i32;
    func setCallingConv(f: Function*);
    func verifyFunction(f: Function*): bool;
    
    func make_stdout(): Value*;
    
    func create_bb(): BasicBlock*;
    func create_bb2(f: Function*): BasicBlock*;
    func SetInsertPoint(bb: BasicBlock*);
    func GetInsertBlock(): BasicBlock*;
    func func_insert(f: Function*, bb: BasicBlock*);
    
    func Value_setName(v: Value*, name: i8*);
    func Value_getType(val: Value*): llvm_Type*;
    func Value_dump(v: Value*);
    func Type_dump(t: llvm_Type*);
    func CreateAlloca(ty: llvm_Type*): Value*;
    func CreateStore(val: Value*, ptr: Value*);
    func CreateMemCpy(trg: Value*, src: Value*, size: i64);
    func CreateRet(val: Value*);
    func CreateRetVoid();
    func CreateSExt(val: Value*, type: llvm_Type*): Value*;
    func CreateZExt(val: Value*, type: llvm_Type*): Value*;
    func CreateTrunc(val: Value*, type: llvm_Type*): Value*;
    func CreatePtrToInt(val: Value*, type: llvm_Type*): Value*;
    func CreateStructGEP(ptr: Value*, idx: i32, type: llvm_Type*): Value*;
    func CreateInBoundsGEP(type: llvm_Type *, ptr: Value*, idx: Args*): Value*;
    func CreateGEP(type: llvm_Type*, ptr: Value*, idx: Args*): Value*;
    func CreateGlobalStringPtr(s: i8*): Value*;
    func CreateCall(f: Function*, args: Args*): Value*;
    func CreateUnreachable();
    func CreateCondBr(cond: Value*, true_bb: BasicBlock*, false_bb: BasicBlock*);
    func CreateBr(bb: BasicBlock*);
    func CreateCmp(op: i32, l: Value*, r: Value*): Value*;
    func get_comp_op(op: i8*): i32;
    func CreateLoad(type: llvm_Type*, val: Value*): Value*;
    func getTrue(): Value*;
    func getFalse(): Value*;
    func CreatePHI(type: llvm_Type*, cnt: i32): PHINode*;
    func phi_addIncoming(phi: PHINode*, val: Value*, bb: BasicBlock*);

    func CreateNSWAdd(l: Value*, r: Value*): Value*;
    func CreateNSWSub(l: Value*, r: Value*): Value*;
    func CreateNSWMul(l: Value*, r: Value*): Value*;
    func CreateSub(l: Value*, r: Value*): Value*;
    func CreateSDiv(l: Value*, r: Value*): Value*;
    func CreateSRem(l: Value*, r: Value*): Value*;
    func CreateAnd(l: Value*, r: Value*): Value*;
    func CreateOr(l: Value*, r: Value*): Value*;
    func CreateXor(l: Value*, r: Value*): Value*;
    func CreateShl(l: Value*, r: Value*): Value*;
    func CreateAShr(l: Value*, r: Value*): Value*;
}

func getDefaultTargetTriple2(): CStr{
    let arr = [0u8; 100];
    let ptr = arr.ptr();
    let len = getDefaultTargetTriple(ptr as i8*);
    return CStr::new(arr[0..len + 1]);
}