
name: test

on: [push]

env: 
  last_version: '1.0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "set env"
        run: echo "toolchain_dir=x-toolchain-$last_version-$(uname -m)" >> "$GITHUB_ENV"

      - uses: actions/checkout@v4
      - name: "download toolchain"
        run: |
          gh auth status
          gh release download v$last_version&&echo "download toolchain '$toolchain_dir'"
          unzip $toolchain_dir.zip
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: bootstrap
        run: |
          bin/build.sh $toolchain_dir

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: toolchain
          path: x-toolchain-x64.zip
