
name: test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        lang-version: [ '1.5' ]

    steps:
      - uses: actions/checkout@v4
      - name: myname
        run: |
          ls
          # bash cpp_bridge/x.sh
          # cd bin
          mkdir build
          wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && sudo  ./llvm.sh 19
          bin/x86-64/x bt x2-x64 -root .
          bin/make_toolchain.sh build/x2-x64 . -zip

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: toolchain
          path: x-toolchain-x64.zip

      - name: "test gh"
        run: |
          echo "Testing GitHub Actions"
          gh auth status
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}